version: "3.9"
services:
  postgres:
    image: postgres:14.1
    expose:
      - "5432/tcp"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "7432:5432"
  postgres_test:
    image: postgres:14.1
    expose:
      - "5432/tcp"
    environment:
      POSTGRES_DB: "${POSTGRES_DB_TEST}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    ports:
      - "7532:5432"    
  redis:
    image: redis:6.2.6
    volumes:
      - redisdata:/data
    ports:
      - "7379:6379"
volumes:
  pgdata:
  pgdata_test:
  redisdata: