default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV["POSTGRES_USER"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
test:
  <<: *default
  database: <%= ENV["POSTGRES_DB_TEST"] %>
  port: 7532
production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
